### ISSUE TITLE
HTML/CSS研修レビュー

### ISSUE THREAD

**Issue by szkyudi** [tepy-pr/kenshu-frontend#1]
# HTML

## コメント
要素の分け方が明確で、読みやすいコードになっていて良いと思います！
いくつか気になる点を記載したのでご確認ください。

## 気になる点

`ul` 要素には `li` `script` `template` 要素しか許可されていないので `div` は使わないようにしましょう。
また、区切り線は文書としての意味を持たず、デザインのための区切り線なので CSS のみで実装できるとなお良いです。

参考: https://developer.mozilla.org/ja/docs/Web/HTML/Element/ul

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L27-L39
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L49-L61
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L67-L82
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L442-L452

---

より適切なタグを使ってもう少し意味付けさせてあげると良いと思います。

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L90-L215
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L225-L354
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L357-L384
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L393-L404
---

`main` 要素は文書のアウトラインに寄与しません。つまり、ページの主要な部分と定義するだけで文書の構造は変化しません。
なので、`main` の下に他の箇所と同様に `section` などを配置して文書に意味付けしてあげましょう。

また、サイドバーはメインのコンテンツとはならないと思うので、`main` 要素の外に配置してあげると良いでしょう。

参考: https://developer.mozilla.org/ja/docs/Web/HTML/Element/main

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/index.html#L219

---

所々で閉じタグがなかったりして、構造が崩れているので、確認して修正してください。

**Comment by szkyudi** [comment]
# CSS
## コメント
CSSのモダンなプロパティや機能を利用していてとても良いと思います。
いくつか気になる点を記載したのでご確認ください。

## 気になる点

Grid Layout を使う意識はとても良いです！
ただ、現状だとブラウザの対応状況があまり良くないので、Flexbox で対応していただけると助かります。

他の箇所も同様です。

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L259-L264

---

親要素で `display: flex` を用いているので、より適切な横幅の指定方法があるかと思います。

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L192-L197

---

親要素で `display: grid` で横幅を指定しているので、こちらで横幅を指定しなくても動作するはずです。
出来る限りコードの依存性を低くできるように心がけましょう。

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L309-L314

---

`line-height` は単位なし数値で指定するのが好ましいので、可能な限りそのように指定しましょう。

参考: https://developer.mozilla.org/ja/docs/Web/CSS/line-height

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L86

---

こちら、もう少し短縮した一括指定プロパティがあります。

参考:  https://developer.mozilla.org/ja/docs/Web/CSS/padding

https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L382-L385
https://github.com/tepy-pr/kenshu-frontend/blob/448591a0cceb18011419a42f89979c38b6437560/src/styles/index.css#L418-L420

**Comment by szkyudi** [comment]
LGTMです！

**Comment by tepy-pr** [comment]
レビューありがとうございました！
